<?php

/**
 * ProductCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    SimpleCart
 * @subpackage Models
 * @author     Jonathan Bernardi <spekkionu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ProductCategory extends Base_ProductCategory
{

}