<?php

/**
 * User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class User extends Base_User
{
    
    public function setPassword($password)
    {
        return $this->_set('password', self::encryptPassword($password));
    }
    
    public static function encryptPassword($password){
      $crypt_key = 'fdhjhkHGFJUyjnmmukRGRGhyjktyyreHGFJrthrGJHTYJgfjhewTJH';
      return hash('sha512', $password.$crypt_key);
      
    }

}