<?php

/**
 * Table_Address
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_Address extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Table_Address
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Address');
    }
}