<?php

/**
 * Table_BillingAddress
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_BillingAddress extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object Table_BillingAddress
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('BillingAddress');
  }

}