<?php

/**
 * Table_Category
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_Category extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Table_Category
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }


    /**
     * Returns category tree
     * @return array
     */
    public function getCategoryTree(){
      $q = Doctrine_Query::create();
      $q->select('id,name,level');
      $q->from('Category');
      $q->setHydrationMode(Doctrine::HYDRATE_ARRAY_HIERARCHY);
      $treeObject = $this->getTree();
      $treeObject->setBaseQuery($q);
      return $treeObject->fetchTree();
    }
}