<?php

/**
 * Table_Customer
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Simplecart
 * @subpackage Model
 * @author     spekkionu
 * @license New BSD http://www.opensource.org/licenses/bsd-license.php
 */
class Table_Customer extends Table_User
{

  /**
   * Returns an instance of this class.
   *
   * @return object Table_Customer
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Customer');
  }

}