<?php

/**
 * Table_OrderedItem
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_OrderedItem extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object Table_OrderedItem
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('OrderedItem');
  }

}