<?php

/**
 * Table_ProductCategory
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_ProductCategory extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object Table_ProductCategory
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('ProductCategory');
  }

}