<?php

/**
 * Table_Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_Product extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Table_Product
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Product');
    }
}