<?php

/**
 * Table_Product
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    Simplecart
 * @subpackage Model
 * @author     spekkionu
 * @license New BSD http://www.opensource.org/licenses/bsd-license.php
 */
class Table_Product extends Doctrine_Table
{

  public static $sortable = array(
    'id', 'sku', 'name', 'price', 'path', 'active'
  );

  /**
   * Returns an instance of this class.
   *
   * @return object Table_Product
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Product');
  }

  /**
   * Return paginated list of products
   * Used for admin list page
   * @param int $page
   * @param int $rowsPerPage
   * @return Zend_Paginator
   */
  public function getAllProducts($page=1, $rowsPerPage = 50, $sort = 'id', $dir = 'asc') {
    $sort = mb_strtolower($sort);
    if (!in_array($sort, self::$sortable)) {
      $sort = 'id';
    }
    $dir = mb_strtoupper($dir);
    if (!in_array($dir, array('ASC', 'DESC'))) {
      $dir = 'ASC';
    }
    // Setup Query
    $q = Doctrine_Query::create()->from('Product');
    $q->orderBy("{$sort} {$dir}");
    $q->setHydrationMode(Doctrine::HYDRATE_ARRAY);
    // Init Pagination
    return SimpleCart_Paginator::getDoctrinePaginator($q, $page, $rowsPerPage);
  }

}