<?php

/**
 * Table_Setting
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_Setting extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Table_Setting
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Setting');
    }
}