<?php

/**
 * Table_ShippingRate
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_ShippingRate extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object Table_ShippingRate
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('ShippingRate');
  }

}