<?php

/**
 * Table_ShippingAddress
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_ShippingAddress extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object Table_ShippingAddress
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('ShippingAddress');
  }

}