<?php

/**
 * Table_Transaction
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Table_Transaction extends Doctrine_Table
{

  /**
   * Returns an instance of this class.
   *
   * @return object Table_Transaction
   */
  public static function getInstance() {
    return Doctrine_Core::getTable('Transaction');
  }

}