<?php $this->headTitle('Manage Categories');?>
<?php $this->pageHeader = 'Manage Categories'; ?>


<?php $this->jQuery()->addJavascriptFile($this->baseUrl('assets/scripts/jquery/jstree/jquery.jstree.js')); ?>
<?php $this->jQuery()->addStylesheet($this->baseUrl('assets/scripts/jquery/jstree/themes/default/style.css')); ?>

<script type="text/javascript">
$(function() {
  $("#category-tree").jstree({
    plugins : [ "themes", "json_data", "ui", "dnd", "types" ],
    ui: { select_limit: 1 },
    types: {
      valid_children : [ "root" ],
      types: {
        "default": { valid_children: ["default"] },
        "root": {
          hover_node : false,
          valid_children: ["default"],
          select_node: function () {return false;}
        }
      }
    },
    json_data: { data: <?php echo Zend_Json::encode($this->categories);?> },
    dnd: { copy_modifier: false }
  })
  .bind("select_node.jstree", function(e, data){
    var url = "<?php echo $this->route('admin_category_details');?>/";
    var selected = data.inst.get_selected();
    if(!selected){
      // If no nodes are selected, clear details
      $('#category-details').hide().empty();
      return;
    }
    var id = $(selected).data("id");
    $('#category-details .ui-button').button( "disable" );
    // Load Details
    $('#category-details').load(url+id, function(responseText, textStatus, XMLHttpRequest){
      $('#category-details').show();
    });
  })
  .bind("deselect_node.jstree", function(e, data){
    var selected = data.inst.get_selected();
    $('#category-details').hide().empty();
  })
  .bind("move_node.jstree", function (e, data) {
		data.rslt.o.each(function (i) {
      data.inst.lock()
			$.ajax({
				type: 'POST',
				url: "<?php echo $this->route('admin_category_move');?>",
				data : {
					"category" : $(this).data("id"),
          "ref": data.rslt.r.data("id"),
          "position": data.rslt.p
				},
				success : function (response) {
          if(!response.success){
            // The move request failed
            data.inst.unlock();
            $.jstree.rollback(data.rlbk);
            simplecart.alert("Error", response.message);
          }
				},
        error: function(){
          // The move request failed
          data.inst.unlock();
          $.jstree.rollback(data.rlbk);
          simplecart.alert("Error", "Failed to move category.");
        }
			});
		});
	});;
});
</script>

<div class="clearfix">
  <div id="category-tree"></div>
  <div id="category-details" class="ui-helper-hidden"></div>
</div>