<?php

/**
 * Base_Admin
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $firstname
 * @property string $lastname
 * @property boolean $active
 * @property enum $accesslevel
 * @property timestamp $signup_date
 * @property timestamp $last_login
 * @property string $token
 * @property string $password_key
 * @property date $token_date
 * 
 * @package    SimpleCart
 * @subpackage Models
 * @author     Jonathan Bernardi <spekkionu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Admin extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('admin');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('username', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'notblank' => true,
             'unique' => true,
             'length' => '15',
             ));
        $this->hasColumn('password', 'string', 128, array(
             'type' => 'string',
             'fixed' => 1,
             'notblank' => true,
             'notnull' => true,
             'length' => '128',
             ));
        $this->hasColumn('email', 'string', 127, array(
             'type' => 'string',
             'email' => true,
             'notnull' => true,
             'notblank' => true,
             'unique' => true,
             'length' => '127',
             ));
        $this->hasColumn('firstname', 'string', 32, array(
             'type' => 'string',
             'notblank' => true,
             'notnull' => true,
             'length' => '32',
             ));
        $this->hasColumn('lastname', 'string', 64, array(
             'type' => 'string',
             'notblank' => true,
             'notnull' => true,
             'length' => '64',
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             'notnull' => true,
             'unsigned' => true,
             ));
        $this->hasColumn('accesslevel', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'admin',
              1 => 'superadmin',
             ),
             'default' => 'admin',
             'notnull' => true,
             'notblank' => true,
             ));
        $this->hasColumn('signup_date', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('token', 'string', 128, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => '128',
             ));
        $this->hasColumn('password_key', 'string', 128, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => '128',
             ));
        $this->hasColumn('token_date', 'date', null, array(
             'type' => 'date',
             ));


        $this->index('login', array(
             'fields' => 
             array(
              0 => 'username',
              1 => 'password',
              2 => 'active',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'created' => 
             array(
              'name' => 'signup_date',
              'type' => 'timestamp',
             ),
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}