<?php

/**
 * Base_OrderedItem
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property integer $order_id
 * @property string $sku
 * @property string $product_name
 * @property integer $quantity
 * @property decimal $price
 * @property decimal $linetotal
 * @property Order $Order
 *
 * @package    SimpleCart
 * @subpackage Models
 * @author     Jonathan Bernardi <spekkionu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_OrderedItem extends Doctrine_Record
{

  public function setTableDefinition() {
    $this->setTableName('ordered_item');
    $this->hasColumn('id', 'integer', 4, array(
      'type' => 'integer',
      'primary' => true,
      'unsigned' => true,
      'autoincrement' => true,
      'length' => '4',
    ));
    $this->hasColumn('order_id', 'integer', 4, array(
      'type' => 'integer',
      'notnull' => true,
      'notblank' => true,
      'unsigned' => true,
      'length' => '4',
    ));
    $this->hasColumn('sku', 'string', 50, array(
      'type' => 'string',
      'length' => '50',
    ));
    $this->hasColumn('product_name', 'string', 100, array(
      'type' => 'string',
      'length' => '100',
    ));
    $this->hasColumn('quantity', 'integer', 2, array(
      'type' => 'integer',
      'unsigned' => true,
      'notnull' => true,
      'default' => 1,
      'length' => '2',
    ));
    $this->hasColumn('price', 'decimal', 8, array(
      'type' => 'decimal',
      'length' => 8,
      'scale' => 2,
      'unsigned' => true,
    ));
    $this->hasColumn('linetotal', 'decimal', 8, array(
      'type' => 'decimal',
      'length' => 8,
      'scale' => 2,
      'unsigned' => true,
    ));
  }

  public function setUp() {
    parent::setUp();
    $this->hasOne('Order', array(
      'local' => 'order_id',
      'foreign' => 'id',
      'owningSide' => true));
  }

}