<?php

/**
 * Base_ShippingRate
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property enum $type
 * @property decimal $min
 * @property decimal $max
 * 
 * @package    Simplecart
 * @subpackage Model
 * @author     spekkionu <spekkionu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_ShippingRate extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('shipping_rate');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('type', 'enum', 9, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'number',
              1 => 'weight',
              2 => 'flatrate',
              3 => 'flatvalue',
             ),
             'length' => 9,
             'default' => 'flatvalue',
             'notnull' => true,
             'notblank' => true,
             ));
        $this->hasColumn('min', 'decimal', 8, array(
             'type' => 'decimal',
             'length' => 8,
             'scale' => 4,
             ));
        $this->hasColumn('max', 'decimal', 8, array(
             'type' => 'decimal',
             'length' => 8,
             'scale' => 4,
             'default' => 0,
             'notblank' => true,
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}