<?php

/**
 * Base_ShippingAddress
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $order_id
 * @property string $company
 * @property string $firstname
 * @property string $lastname
 * @property string $address
 * @property string $address2
 * @property string $city
 * @property string $state
 * @property string $zip
 * @property string $phone
 * @property Order $Order
 * 
 * @package    SimpleCart
 * @subpackage Models
 * @author     Jonathan Bernardi <spekkionu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_ShippingAddress extends Doctrine_Record
{
    public function setTableDefinition()
    {
        $this->setTableName('shipping_address');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'unsigned' => true,
             'autoincrement' => true,
             'length' => '4',
             ));
        $this->hasColumn('order_id', 'integer', 4, array(
             'type' => 'integer',
             'unsigned' => true,
             'notnull' => true,
             'notblank' => true,
             'length' => '4',
             ));
        $this->hasColumn('company', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('firstname', 'string', 32, array(
             'type' => 'string',
             'length' => '32',
             ));
        $this->hasColumn('lastname', 'string', 64, array(
             'type' => 'string',
             'length' => '64',
             ));
        $this->hasColumn('address', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('address2', 'string', 100, array(
             'type' => 'string',
             'length' => '100',
             ));
        $this->hasColumn('city', 'string', 40, array(
             'type' => 'string',
             'length' => '40',
             ));
        $this->hasColumn('state', 'string', 2, array(
             'type' => 'string',
             'fixed' => 1,
             'usstate' => true,
             'length' => '2',
             ));
        $this->hasColumn('zip', 'string', 5, array(
             'type' => 'string',
             'fixed' => 1,
             'length' => '5',
             ));
        $this->hasColumn('phone', 'string', 25, array(
             'type' => 'string',
             'length' => '25',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Order', array(
             'local' => 'order_id',
             'foreign' => 'id',
             'owningSide' => true));
    }
}