<?php

/**
 * Base_Transaction
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @property integer $id
 * @property integer $order_id
 * @property string $tranaction_id
 * @property string $parent_transaction_id
 * @property string $type
 * @property decimal $amount
 * @property string $authcode
 * @property string $authreason
 * @property string $errormessage
 * @property boolean $is_primary
 * @property Order $Order
 *
 * @package    SimpleCart
 * @subpackage Models
 * @author     Jonathan Bernardi <spekkionu@gmail.com>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class Base_Transaction extends Doctrine_Record
{

  public function setTableDefinition() {
    $this->setTableName('transaction');
    $this->hasColumn('id', 'integer', 4, array(
      'type' => 'integer',
      'primary' => true,
      'unsigned' => true,
      'autoincrement' => true,
      'length' => '4',
    ));
    $this->hasColumn('order_id', 'integer', 4, array(
      'type' => 'integer',
      'unsigned' => true,
      'notnull' => true,
      'notblank' => true,
      'length' => '4',
    ));
    $this->hasColumn('tranaction_id', 'string', 127, array(
      'type' => 'string',
      'length' => '127',
    ));
    $this->hasColumn('parent_transaction_id', 'string', 127, array(
      'type' => 'string',
      'length' => '127',
    ));
    $this->hasColumn('type', 'string', 30, array(
      'type' => 'string',
      'length' => '30',
    ));
    $this->hasColumn('amount', 'decimal', 8, array(
      'type' => 'decimal',
      'length' => 8,
      'scale' => 2,
    ));
    $this->hasColumn('authcode', 'string', 50, array(
      'type' => 'string',
      'length' => '50',
    ));
    $this->hasColumn('authreason', 'string', 255, array(
      'type' => 'string',
      'length' => '255',
    ));
    $this->hasColumn('errormessage', 'string', 50, array(
      'type' => 'string',
      'length' => '50',
    ));
    $this->hasColumn('is_primary', 'boolean', null, array(
      'type' => 'boolean',
      'default' => false,
      'notblank' => true,
      'notnull' => true,
      'unsigned' => true,
    ));
  }

  public function setUp() {
    parent::setUp();
    $this->hasOne('Order', array(
      'local' => 'order_id',
      'foreign' => 'id',
      'owningSide' => true));

    $timestampable0 = new Doctrine_Template_Timestampable(array(
        'created' =>
        array(
          'name' => 'transaction_date',
          'type' => 'timestamp',
        ),
        'updated' =>
        array(
          'disabled' => true,
        ),
      ));
    $this->actAs($timestampable0);
  }

}