<?php echo $this->doctype('HTML5');?>
<html lang="en">
<head>
<?php
$this->headMeta()->setCharset('utf8');
echo $this->headMeta();

$this->headTitle($this->site_info['name'].' Administration', 'PREPEND')->setSeparator(' - ');
echo $this->headTitle();

// CSS Files
//$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/admin.min.css'), 'screen');
$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/base.css'), 'screen');
$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/admin.css'), 'screen');
$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/admin-menu.css'), 'screen');
$this->headLink()->appendStylesheet($this->baseUrl('assets/scripts/jquery/jquery.ui/css/cupertino/jquery-ui-1.8.16.custom.css'));
$this->headLink()->appendStylesheet($this->baseUrl('assets/scripts/jquery/jquery-validate.password/jquery.validate.password.css'));

$this->headLink()->appendStylesheet($this->baseUrl('assets/styles/ie.css'), 'screen', 'lt IE 8');
echo $this->headLink();

// Javascript Files
$this->headScript()->appendFile($this->baseUrl('assets/scripts/html5.js'), 'text/javascript', array('conditional' => 'lt IE 9'));

//$this->headScript()->appendFile($this->baseUrl('assets/scripts/admin.min.js'), 'text/javascript');
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/jquery-1.6.4.min.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/jquery.ui/js/jquery-ui-1.8.16.custom.min.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/jquery.metadata.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/superfish/js/hoverIntent.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/jquery.bgiframe-2.1.2.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/superfish/js/superfish.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/superfish/js/supersubs.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/jquery.form.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/jquery-validation/jquery.validate.min.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/jquery-validation/additional-methods.min.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/jquery/jquery-validate.password/jquery.validate.password.js'));
$this->headScript()->appendFile($this->baseUrl('assets/scripts/simplecart.js'));
echo $this->headScript();

// jQuery Plugins
$this->jQuery()->enable()->uiEnable();
$this->jQuery()->setRenderMode(ZendX_JQuery::RENDER_ALL ^ ZendX_JQuery::RENDER_LIBRARY);
$this->jQuery()->setLocalPath($this->baseUrl('assets/scripts/jquery/jquery-1.6.4.min.js'));
$this->jQuery()->setUiLocalPath($this->baseUrl('assets/scripts/jquery/jquery.ui/js/jquery-ui-1.8.16.custom.min.js'));

echo $this->jQuery();

echo $this->headStyle();
?>
<?php echo $this->placeholder('headExtra'); ?>
</head>
<body>
  <header class="main-header">
    <h1 class="site-title"><?php echo $this->escape($this->site_info['name']);?> Administration</h1>
    <?php if(Zend_Auth::getInstance()->hasIdentity()):?>
      <div class="welcome-message-container">
        <div class="welcome-message">Welcome, <?php echo $this->escape($this->identity->username);?></div>
        <nav class="header-navigation">
          <a class="ui-button ui-widget ui-state-default ui-corner-all" data-icon="icon-user" href="<?php echo $this->urlLink('admin', 'account');?>" title="Manage account profile">My Account</a>
          <a class="ui-button ui-widget ui-state-default ui-corner-all" data-icon="icon-logout" href="<?php echo $this->urlLink('admin', 'access', 'logout');?>" title="Log out">Log Out</a>
        </nav>
      </div>
    <?php endif;?>
    <nav class="main-navigation clearfix">
      <?php echo $this->navigation()->menu()->setUlClass('sf-menu')->render() ?>
    </nav>
  </header>
  <section class="content-container">
    <header class="content-header">
      <?php if($this->pageHeader):?>
        <h1 class="page-title"><?php echo $this->escape($this->pageHeader);?></h1>
      <?php endif;?>
      <nav class="breadcrumbs">
        <?php if($this->url() != $this->route('admin_home')):?>
          <a href="<?php echo $this->route('admin_home');?>" title="Admin Dashboard">Dashboard</a> &#187;
        <?php endif;?>
        <?php echo $this->navigation()->breadcrumbs()->setLinkLast(FALSE)->setMinDepth(0)->setSeparator(" &#187; ".PHP_EOL); ?>
      </nav>
      <?php echo $this->flashMessages();?>
    </header>
    <div class="content">
      <?php echo $this->layout()->content;?>
    </div>
  </section>
  <footer class="site-footer">
    &copy; copyright <?php echo date('Y');?> <a href="http://simplecart.spekkionu.com" target="_blank">spekkionu</a>
  </footer>
</body>
</html>